# Generated by Django 5.0.3 on 2024-03-29 15:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("weight", models.IntegerField()),
                ("height", models.IntegerField()),
                ("illness", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "goal",
                    models.CharField(
                        choices=[
                            ("hypertrophy", "Hypertrophy"),
                            ("maintenance", "Maintenance"),
                            ("weight_loss", "Weight Loss"),
                        ],
                        default="maintenance",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
