# Generated by Django 5.0.3 on 2024-03-29 15:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="diet",
            field=models.CharField(
                choices=[
                    ("vegetarian", "Vegetarian"),
                    ("ornivorous", "Ornivorous"),
                    ("paleolithic", "Paleolithic"),
                    ("mediterranean", "Mediterranean"),
                    ("ketogenic", " ketogenic"),
                ],
                default="ornivorous",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                default="male",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="intolerance",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="user",
            field=models.OneToOneField(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="height",
            field=models.FloatField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="weight",
            field=models.FloatField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
