# Generated by Django 5.0.3 on 2024-03-29 22:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "age",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "weight",
                    models.FloatField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "height",
                    models.FloatField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("illness", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "intolerance",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "goal",
                    models.CharField(
                        choices=[
                            ("hypertrophy", "Hypertrophy"),
                            ("maintenance", "Maintenance"),
                            ("weight_loss", "Weight Loss"),
                        ],
                        default="maintenance",
                        max_length=20,
                    ),
                ),
                (
                    "diet",
                    models.CharField(
                        choices=[
                            ("vegetarian", "Vegetarian"),
                            ("ornivorous", "Ornivorous"),
                            ("paleolithic", "Paleolithic"),
                            ("mediterranean", "Mediterranean"),
                            ("ketogenic", " ketogenic"),
                        ],
                        default="ornivorous",
                        max_length=20,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")],
                        default="male",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
